
version: '3.8'

services:
  postgress:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: vansh
      POSTGRES_PASSWORD: vansh123
      POSTGRES_DB: counter
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://vansh:vansh123@localhost:5432/counter
    depends_on:
      - postgres

volumes:
  postgres_data:
